files: ^(pytest_playwright_enhanced|scripts|tests|changes)
repos:
  # An identity hook that writes files to check to stdout.
  - repo: meta
    hooks:
      - id: identity
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/twisted/towncrier
    rev: 23.11.0
    hooks:
      - id: towncrier-check
      # unused for now.- id: towncrier-update
        files: changes/
        args: ['--keep']