site_name: Pytest Playwright Enhanced
site_description: Pytest plugin for playwright python bindings
site_url: "https://symonk.github.io/pytest-playwright-enhanced/"
theme:
  name: material
  language: en
  icon:
    logo: bootstrap/envelope-paper
    menu:
    alternate:
    search:
    share:
    close:
    top:
    edit:
    view:
    repo:
    admonition:
    tag:
    previous:
    next:
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: light blue
      accent: deep orange

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins 
    code: Poppins 
  icon:
    repo: fontawesome/brands/github
repo_name: pytest-playwright-enhanced
repo_url: https://github.com/symonk/pytest-playwright-enhanced/
edit_uri: ""
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
 - stylesheets/extra.css
watch:
  - pytest_playwright_enhanced
nav:
    - Quickstart: index.md
    - Installation: install.md 
    - Commandline Arguments: cli.md
    - Fixtures: fixtures.md
    - Hooks: hooks.md
plugins:
    - search
    - social:
        cards_layout_options:
          font_family: Poppins
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              heading_level: 2
              show_root_heading: true
              show_symbol_type_heading: true
              docstring_style: sphinx
              line_length: 120
              show_if_no_docstring: true
              merge_init_into_class: true
              show_source: true
              docstring_section_style: spacy
              show_bases: false
              show_symbol_type_toc: true
              annotations_path: brief
              show_signature_annotations: false
              separate_signature: true
              unwrap_annotated: true
              show_docstring_returns: true
              show_docstring_yields: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
copyright: >
  Copyright &copy; 2024 Simon Kerr - 
  <a href="#__consent">Change cookie settings</a>