name: pytest playwright enhanced testing 
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py38",
          "ubuntu-py39",
          "ubuntu-py310",
          "windows-py310",
        ]
        include:
          - name: "windows-py310"
            python: "3.10"
            os: "windows-latest"
            tox_env: "py310"
            do_cov: false
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-20.04
            tox_env: "py38"
            do_cov: false
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-20.04
            tox_env: "py39"
            do_cov: false
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-20.04
            tox_env: "py310"
            do_cov: true
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python ${{ matrix.python }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install poetry
          pip --version
          tox --version
          poetry --version
          poetry install
          poetry run python -m playwright install --with-deps

      - name: Test without coverage
        if: "! matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}

      - name: Test with coverage
        if: "matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}

      - name: Generate cov report
        if: "matrix.do_cov"
        run: |
          tox -e report_cov

      - name: Upload to CodeCov
        if: "matrix.do_cov"
        uses: codecov/codecov-action@v4
        with:
          flags: pytest_playwright_enhanced_unit_tests 
          fail_ci_if_error: true
          verbose: true